### ISSUE TITLE
How to get debug info when working on u-boot support?

### ISSUE THREAD

**Issue by MYEUHD** [fourkbomb/u-boot#1]
Hi,
I'm interested in making aries (codename for 1st gen Galaxy S devices) work with u-boot as a PBL and SBL.
You said in your blogpost about u-boot in the galaxy s3 that the second basic step was to: "Check that the BL2 works at least well enough to write stuff out to UART."
I'm curious, is there a way to get debug info before reaching that state?

Thanks!

**Comment by fourkbomb** [comment]
Not easily... I had access to a vendor u-boot dump which had been adapted to boot on i9300 (https://github.com/dmarszk/exynos4_uboot/). My debugging method was basically to manually trace through the assembler and figure out what was being done differently.

I guess if you're writing u-boot to  the sdcard you might be able to get it to write stuff to RAM somewhere and read it from the Samsung PBL/SBL when booting without the sdcard (That's just a thought - I don't really know how you'd do this)
